### ISSUE TITLE
Problem with cookie

### ISSUE THREAD

**Issue by develmusa** [MaxGfeller/recipe-downloader#1]
Which cookie should I use? I have tried them all and I only get jpeg's with the size of 1.1KiB
![xxxxx](https://user-images.githubusercontent.com/9266221/80789957-d6495080-8b8d-11ea-9e78-4c9f60f43e5f.png)

**Comment by Magbert1** [comment]
Würde mich auch interessieren, welches Cookie hier gemeint ist. Ich kriege auch nur Unmengen von korrupten jpegs

**Comment by MaxGfeller** [comment]
Betty Bossi doesn't have this offer anymore, so it won't work any longer. But feel free to write me an email (address in profile) and i'll see if i can help you.
